-- Issue #278: rimozione dei grant EXECUTE residui a PUBLIC/anon sulle funzioni SECURITY DEFINER.

DO $$
BEGIN
  BEGIN REVOKE EXECUTE ON FUNCTION public.admin_assign_station(integer, bigint) FROM PUBLIC, anon; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REVOKE EXECUTE ON FUNCTION public.admin_delete_user(integer) FROM PUBLIC, anon; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REVOKE EXECUTE ON FUNCTION public.check_rate_limit(text, text, integer, integer) FROM PUBLIC, anon; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REVOKE EXECUTE ON FUNCTION public.cleanup_old_rate_limits() FROM PUBLIC, anon; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REVOKE EXECUTE ON FUNCTION public.current_user_id() FROM PUBLIC, anon; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REVOKE EXECUTE ON FUNCTION public.current_user_station_ids() FROM PUBLIC, anon; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REVOKE EXECUTE ON FUNCTION public.delete_voucher_photo() FROM PUBLIC, anon; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REVOKE EXECUTE ON FUNCTION public.get_current_user_id() FROM PUBLIC, anon; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REVOKE EXECUTE ON FUNCTION public.is_operator() FROM PUBLIC, anon; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REVOKE EXECUTE ON FUNCTION public.is_station_operator(bigint) FROM PUBLIC, anon; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REVOKE EXECUTE ON FUNCTION public.notify_admin_crediti_modifica() FROM PUBLIC, anon; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REVOKE EXECUTE ON FUNCTION public.reset_rate_limit(text, text) FROM PUBLIC, anon; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REVOKE EXECUTE ON FUNCTION public.set_created_by_auth() FROM PUBLIC, anon; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REVOKE EXECUTE ON FUNCTION public.set_users_created_by_auth() FROM PUBLIC, anon; EXCEPTION WHEN OTHERS THEN NULL; END;
END $$;
