-- Migration: Customer Refunds & Non-erogato
-- Date: 2026-07-23

BEGIN;

CREATE TABLE IF NOT EXISTS public.customer_refunds (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift_id bigint NOT NULL REFERENCES public.shifts(id) ON DELETE CASCADE,
  station_id bigint NOT NULL REFERENCES public.fuel_stations(id),
  operator_id bigint REFERENCES public.users(id),
  amount numeric(12,2) NOT NULL CHECK (amount > 0),
  receipt_date date NOT NULL,
  method text NOT NULL CHECK (method IN ('cash','erogation')),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.customer_refunds IS 'Rimborsi clienti per banconote incassate ma non erogate (self-service). Method cash = restituzione contante; erogation = erogazione carburante a rimborso.';

-- Enable RLS
ALTER TABLE public.customer_refunds ENABLE ROW LEVEL SECURITY;

-- RLS Policy
DROP POLICY IF EXISTS customer_refunds_policy ON public.customer_refunds;
CREATE POLICY customer_refunds_policy ON public.customer_refunds
  FOR ALL
  TO authenticated
  USING (
    public.is_admin() OR public.is_station_operator(station_id)
  )
  WITH CHECK (
    public.is_admin() OR public.is_station_operator(station_id)
  );

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION public.update_customer_refunds_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_customer_refunds_updated_at ON public.customer_refunds;
CREATE TRIGGER trg_customer_refunds_updated_at
  BEFORE UPDATE ON public.customer_refunds
  FOR EACH ROW
  EXECUTE FUNCTION public.update_customer_refunds_updated_at();

-- RPC Function: create_customer_refund
CREATE OR REPLACE FUNCTION public.create_customer_refund(
  p_shift_id bigint,
  p_station_id bigint,
  p_amount numeric,
  p_receipt_date date,
  p_method text,
  p_notes text DEFAULT ''
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_refund public.customer_refunds%ROWTYPE;
BEGIN
  -- 1. Check auth.uid() IS NOT NULL
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;

  -- 2. Check operator belongs to station or is admin
  IF NOT public.is_admin() AND NOT public.is_station_operator(p_station_id) THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;

  -- 3. Check shift exists, is open and belongs to station
  IF NOT EXISTS (
    SELECT 1
    FROM public.shifts
    WHERE id = p_shift_id
      AND station_id = p_station_id
      AND status = 'open'
      AND closed_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Shift non valido o non aperto per questa stazione';
  END IF;

  IF p_amount <= 0 THEN
    RAISE EXCEPTION 'Importo non valido';
  END IF;

  IF p_method NOT IN ('cash', 'erogation') THEN
    RAISE EXCEPTION 'Metodo di rimborso non valido';
  END IF;

  -- 4. Insert into public.customer_refunds
  INSERT INTO public.customer_refunds (
    shift_id,
    station_id,
    operator_id,
    amount,
    receipt_date,
    method,
    notes
  )
  VALUES (
    p_shift_id,
    p_station_id,
    public.current_user_id(),
    p_amount,
    p_receipt_date,
    p_method,
    p_notes
  )
  RETURNING * INTO v_refund;

  -- 5. Return row JSON
  RETURN to_jsonb(v_refund);
END;
$$;

GRANT ALL ON TABLE public.customer_refunds TO authenticated;
REVOKE ALL ON FUNCTION public.create_customer_refund(bigint, bigint, numeric, date, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_customer_refund(bigint, bigint, numeric, date, text, text) TO authenticated;

NOTIFY pgrst, 'reload schema';

COMMIT;
